name: language-dockerfile
version: '0.3.6.0'
synopsis: Dockerfile linter, parser, pretty-printer and embedded DSL
description: '
Forked from @hadolint@.


All functions for parsing, printing and writting Dockerfiles are exported
through @Language.Dockerfile@. For more fine-grained operations look for
specific modules that implement a certain functionality.

See the <https://github.com/lorenzo/haskell-language-dockerfile GitHub project> for the source-code and examples.
'
category: Development
author:
- Lukas Martinelli
- Pedro Tacla Yamada
- José Lorenzo Rodríguez
maintainer: lorenzo@seatgeek.com
copyright:
- Lukas Martinelli, Copyright (c) 2016
- Pedro Tacla Yamada, Copyright (c) 2016
- José Lorenzo Rodríguez, Copyright (c) 2016
license: GPL-3
github: lorenzo/language-dockerfile
extra-source-files:
- README.md

dependencies:
- base >=4.8 && <5
- bytestring >=0.10
- parsec >=3.1
- pretty
- split >=0.2
- free
- mtl
- transformers
- template-haskell
- th-lift
- th-lift-instances

- text
- yaml
- aeson
- Glob
- unordered-containers
- directory
- filepath

library:
  source-dirs: src
  exposed-modules:
  - Language.Dockerfile
  - Language.Dockerfile.Parser
  - Language.Dockerfile.Predef
  - Language.Dockerfile.PrettyPrint
  - Language.Dockerfile.Normalize
  - Language.Dockerfile.Syntax
  - Language.Dockerfile.Lexer
  - Language.Dockerfile.Syntax.Lift
  - Language.Dockerfile.EDSL
  - Language.Dockerfile.EDSL.Quasi
  - Language.Dockerfile.EDSL.Types

tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - hspec
    - QuickCheck
    - language-dockerfile
    - Glob
    - directory
    - filepath
    - process
    - HUnit >=1.2
